# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vicente/Escritorio/POSG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vicente/Escritorio/POSG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vicente/Escritorio/POSG/CMakeFiles /home/vicente/Escritorio/POSG/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vicente/Escritorio/POSG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named posg

# Build rule for target.
posg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 posg
.PHONY : posg

# fast build rule for target.
posg/fast:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/build
.PHONY : posg/fast

src/Astro.o: src/Astro.cpp.o

.PHONY : src/Astro.o

# target to build an object file
src/Astro.cpp.o:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Astro.cpp.o
.PHONY : src/Astro.cpp.o

src/Astro.i: src/Astro.cpp.i

.PHONY : src/Astro.i

# target to preprocess a source file
src/Astro.cpp.i:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Astro.cpp.i
.PHONY : src/Astro.cpp.i

src/Astro.s: src/Astro.cpp.s

.PHONY : src/Astro.s

# target to generate assembly for a file
src/Astro.cpp.s:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Astro.cpp.s
.PHONY : src/Astro.cpp.s

src/Esfera.o: src/Esfera.cpp.o

.PHONY : src/Esfera.o

# target to build an object file
src/Esfera.cpp.o:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Esfera.cpp.o
.PHONY : src/Esfera.cpp.o

src/Esfera.i: src/Esfera.cpp.i

.PHONY : src/Esfera.i

# target to preprocess a source file
src/Esfera.cpp.i:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Esfera.cpp.i
.PHONY : src/Esfera.cpp.i

src/Esfera.s: src/Esfera.cpp.s

.PHONY : src/Esfera.s

# target to generate assembly for a file
src/Esfera.cpp.s:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Esfera.cpp.s
.PHONY : src/Esfera.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Scene.o: src/Scene.cpp.o

.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i

.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s

.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/rotatecb.o: src/rotatecb.cpp.o

.PHONY : src/rotatecb.o

# target to build an object file
src/rotatecb.cpp.o:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/rotatecb.cpp.o
.PHONY : src/rotatecb.cpp.o

src/rotatecb.i: src/rotatecb.cpp.i

.PHONY : src/rotatecb.i

# target to preprocess a source file
src/rotatecb.cpp.i:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/rotatecb.cpp.i
.PHONY : src/rotatecb.cpp.i

src/rotatecb.s: src/rotatecb.cpp.s

.PHONY : src/rotatecb.s

# target to generate assembly for a file
src/rotatecb.cpp.s:
	$(MAKE) -f CMakeFiles/posg.dir/build.make CMakeFiles/posg.dir/src/rotatecb.cpp.s
.PHONY : src/rotatecb.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... posg"
	@echo "... src/Astro.o"
	@echo "... src/Astro.i"
	@echo "... src/Astro.s"
	@echo "... src/Esfera.o"
	@echo "... src/Esfera.i"
	@echo "... src/Esfera.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/rotatecb.o"
	@echo "... src/rotatecb.i"
	@echo "... src/rotatecb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

